# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chandra/ParticleSimulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chandra/ParticleSimulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chandra/ParticleSimulator/CMakeFiles /home/chandra/ParticleSimulator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chandra/ParticleSimulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ParticleSimulator

# Build rule for target.
ParticleSimulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ParticleSimulator
.PHONY : ParticleSimulator

# fast build rule for target.
ParticleSimulator/fast:
	$(MAKE) -f CMakeFiles/ParticleSimulator.dir/build.make CMakeFiles/ParticleSimulator.dir/build
.PHONY : ParticleSimulator/fast

#=============================================================================
# Target rules for targets named BOSClass

# Build rule for target.
BOSClass: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BOSClass
.PHONY : BOSClass

# fast build rule for target.
BOSClass/fast:
	$(MAKE) -f BOSClass/CMakeFiles/BOSClass.dir/build.make BOSClass/CMakeFiles/BOSClass.dir/build
.PHONY : BOSClass/fast

CompositeParticle.o: CompositeParticle.cxx.o
.PHONY : CompositeParticle.o

# target to build an object file
CompositeParticle.cxx.o:
	$(MAKE) -f CMakeFiles/ParticleSimulator.dir/build.make CMakeFiles/ParticleSimulator.dir/CompositeParticle.cxx.o
.PHONY : CompositeParticle.cxx.o

CompositeParticle.i: CompositeParticle.cxx.i
.PHONY : CompositeParticle.i

# target to preprocess a source file
CompositeParticle.cxx.i:
	$(MAKE) -f CMakeFiles/ParticleSimulator.dir/build.make CMakeFiles/ParticleSimulator.dir/CompositeParticle.cxx.i
.PHONY : CompositeParticle.cxx.i

CompositeParticle.s: CompositeParticle.cxx.s
.PHONY : CompositeParticle.s

# target to generate assembly for a file
CompositeParticle.cxx.s:
	$(MAKE) -f CMakeFiles/ParticleSimulator.dir/build.make CMakeFiles/ParticleSimulator.dir/CompositeParticle.cxx.s
.PHONY : CompositeParticle.cxx.s

Gamma.o: Gamma.cxx.o
.PHONY : Gamma.o

# target to build an object file
Gamma.cxx.o:
	$(MAKE) -f CMakeFiles/ParticleSimulator.dir/build.make CMakeFiles/ParticleSimulator.dir/Gamma.cxx.o
.PHONY : Gamma.cxx.o

Gamma.i: Gamma.cxx.i
.PHONY : Gamma.i

# target to preprocess a source file
Gamma.cxx.i:
	$(MAKE) -f CMakeFiles/ParticleSimulator.dir/build.make CMakeFiles/ParticleSimulator.dir/Gamma.cxx.i
.PHONY : Gamma.cxx.i

Gamma.s: Gamma.cxx.s
.PHONY : Gamma.s

# target to generate assembly for a file
Gamma.cxx.s:
	$(MAKE) -f CMakeFiles/ParticleSimulator.dir/build.make CMakeFiles/ParticleSimulator.dir/Gamma.cxx.s
.PHONY : Gamma.cxx.s

Particle.o: Particle.cxx.o
.PHONY : Particle.o

# target to build an object file
Particle.cxx.o:
	$(MAKE) -f CMakeFiles/ParticleSimulator.dir/build.make CMakeFiles/ParticleSimulator.dir/Particle.cxx.o
.PHONY : Particle.cxx.o

Particle.i: Particle.cxx.i
.PHONY : Particle.i

# target to preprocess a source file
Particle.cxx.i:
	$(MAKE) -f CMakeFiles/ParticleSimulator.dir/build.make CMakeFiles/ParticleSimulator.dir/Particle.cxx.i
.PHONY : Particle.cxx.i

Particle.s: Particle.cxx.s
.PHONY : Particle.s

# target to generate assembly for a file
Particle.cxx.s:
	$(MAKE) -f CMakeFiles/ParticleSimulator.dir/build.make CMakeFiles/ParticleSimulator.dir/Particle.cxx.s
.PHONY : Particle.cxx.s

ParticleData.o: ParticleData.cxx.o
.PHONY : ParticleData.o

# target to build an object file
ParticleData.cxx.o:
	$(MAKE) -f CMakeFiles/ParticleSimulator.dir/build.make CMakeFiles/ParticleSimulator.dir/ParticleData.cxx.o
.PHONY : ParticleData.cxx.o

ParticleData.i: ParticleData.cxx.i
.PHONY : ParticleData.i

# target to preprocess a source file
ParticleData.cxx.i:
	$(MAKE) -f CMakeFiles/ParticleSimulator.dir/build.make CMakeFiles/ParticleSimulator.dir/ParticleData.cxx.i
.PHONY : ParticleData.cxx.i

ParticleData.s: ParticleData.cxx.s
.PHONY : ParticleData.s

# target to generate assembly for a file
ParticleData.cxx.s:
	$(MAKE) -f CMakeFiles/ParticleSimulator.dir/build.make CMakeFiles/ParticleSimulator.dir/ParticleData.cxx.s
.PHONY : ParticleData.cxx.s

ParticleSimulator.o: ParticleSimulator.cxx.o
.PHONY : ParticleSimulator.o

# target to build an object file
ParticleSimulator.cxx.o:
	$(MAKE) -f CMakeFiles/ParticleSimulator.dir/build.make CMakeFiles/ParticleSimulator.dir/ParticleSimulator.cxx.o
.PHONY : ParticleSimulator.cxx.o

ParticleSimulator.i: ParticleSimulator.cxx.i
.PHONY : ParticleSimulator.i

# target to preprocess a source file
ParticleSimulator.cxx.i:
	$(MAKE) -f CMakeFiles/ParticleSimulator.dir/build.make CMakeFiles/ParticleSimulator.dir/ParticleSimulator.cxx.i
.PHONY : ParticleSimulator.cxx.i

ParticleSimulator.s: ParticleSimulator.cxx.s
.PHONY : ParticleSimulator.s

# target to generate assembly for a file
ParticleSimulator.cxx.s:
	$(MAKE) -f CMakeFiles/ParticleSimulator.dir/build.make CMakeFiles/ParticleSimulator.dir/ParticleSimulator.cxx.s
.PHONY : ParticleSimulator.cxx.s

WriteFile.o: WriteFile.cxx.o
.PHONY : WriteFile.o

# target to build an object file
WriteFile.cxx.o:
	$(MAKE) -f CMakeFiles/ParticleSimulator.dir/build.make CMakeFiles/ParticleSimulator.dir/WriteFile.cxx.o
.PHONY : WriteFile.cxx.o

WriteFile.i: WriteFile.cxx.i
.PHONY : WriteFile.i

# target to preprocess a source file
WriteFile.cxx.i:
	$(MAKE) -f CMakeFiles/ParticleSimulator.dir/build.make CMakeFiles/ParticleSimulator.dir/WriteFile.cxx.i
.PHONY : WriteFile.cxx.i

WriteFile.s: WriteFile.cxx.s
.PHONY : WriteFile.s

# target to generate assembly for a file
WriteFile.cxx.s:
	$(MAKE) -f CMakeFiles/ParticleSimulator.dir/build.make CMakeFiles/ParticleSimulator.dir/WriteFile.cxx.s
.PHONY : WriteFile.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ParticleSimulator"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BOSClass"
	@echo "... CompositeParticle.o"
	@echo "... CompositeParticle.i"
	@echo "... CompositeParticle.s"
	@echo "... Gamma.o"
	@echo "... Gamma.i"
	@echo "... Gamma.s"
	@echo "... Particle.o"
	@echo "... Particle.i"
	@echo "... Particle.s"
	@echo "... ParticleData.o"
	@echo "... ParticleData.i"
	@echo "... ParticleData.s"
	@echo "... ParticleSimulator.o"
	@echo "... ParticleSimulator.i"
	@echo "... ParticleSimulator.s"
	@echo "... WriteFile.o"
	@echo "... WriteFile.i"
	@echo "... WriteFile.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

